In [28]:
import pandas as pd
import re

In [29]:
df = pd.read_csv('df_final.csv')
df

,name,released,rating,ratings_count,added,reviews_count,genres,platform,game_mode,status_yet,status_owned,status_beaten,status_toplay,status_dropped,status_playing,platform_visual,genres_visual,rating_rango,genres_clean
0,Grand Theft Auto V,2013-09-17,4.47,7334,22482,7457,['Action'],"['PC', 'PlayStation', 'Xbox']",Both,557,12857,6455,649,1185,779,"['PC', 'PlayStation', 'Xbox']",['Action'],"(373.0, 7334.0]",['Action']
1,The Witcher 3: Wild Hunt,2015-05-18,4.64,7142,22119,7261,"['Action', 'RPG']","['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...",Singleplayer,1207,12857,5284,850,1025,896,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...","['Action', 'RPG']","(373.0, 7334.0]","['Action', 'RPG']"
2,Portal 2,2011-04-18,4.58,6066,20829,6123,"['Shooter', 'Puzzle']","['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...",Both,672,13095,5843,410,645,164,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...","['Shooter', 'Puzzle']","(373.0, 7334.0]","['Shooter', 'Puzzle']"
3,Counter-Strike: Global Offensive,2012-08-21,3.57,3626,18342,3664,['Shooter'],"['PC', 'PlayStation', 'Xbox', 'Linux']",Multiplayer,267,14099,1143,80,2120,633,"['PC', 'PlayStation', 'Xbox', 'Linux']",['Shooter'],"(373.0, 7334.0]",['Shooter']
4,Tomb Raider (2013),2013-03-05,4.06,4079,17782,4113,['Action'],"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh']",Both,700,11584,4522,295,564,117,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh']",['Action'],"(373.0, 7334.0]",['Action']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9841,Khan: Absolute Power,2016-03-18,0.00,2,195,2,"['Action', 'Adventure', 'RPG', 'Massively Mult...",['PC'],Other,3,192,1,1,2,1,['PC'],"['Action', 'Adventure', 'RPG', 'Massively Mult...","(-0.001, 17.0]","['Action', 'Adventure', 'RPG', 'Massively Mult..."
9842,I am Weapon: Revival,2015-10-23,2.50,12,195,12,"['Action', 'RPG', 'Indie']",['PC'],Singleplayer,3,186,1,3,2,1,['PC'],"['Action', 'RPG', 'Indie']","(-0.001, 17.0]","['Action', 'RPG', 'Indie']"
9843,PresenZ,2016-04-28,0.00,1,195,1,[],['PC'],Other,2,193,1,1,2,1,['PC'],[],"(-0.001, 17.0]",['Unknown']
9844,Bohemian Killing,2016-07-21,3.18,11,195,11,"['Adventure', 'Simulation', 'Indie']","['PC', 'Apple Macintosh', 'Nintendo']",Singleplayer,13,170,6,4,2,1,"['PC', 'Apple Macintosh', 'Nintendo']","['Adventure', 'Simulation', 'Indie']","(-0.001, 17.0]","['Adventure', 'Simulation', 'Indie']"
9845,Nightork Adventures - Beyond the Moons of Shad...,2016-08-23,0.00,2,195,2,"['Action', 'Simulation', 'Indie']",['PC'],Singleplayer,3,192,1,1,2,1,['PC'],"['Action', 'Simulation', 'Indie']","(-0.001, 17.0]","['Action', 'Simulation', 'Indie']"

In [30]:
df.insert(0, "id", range(0, len(df)))
df.set_index("id", inplace=True)
df.head()

,name,released,rating,ratings_count,added,reviews_count,genres,platform,game_mode,status_yet,status_owned,status_beaten,status_toplay,status_dropped,status_playing,platform_visual,genres_visual,rating_rango,genres_clean
id,,,,,,,,,,,,,,,,,,,
0,Grand Theft Auto V,2013-09-17,4.47,7334,22482,7457,['Action'],"['PC', 'PlayStation', 'Xbox']",Both,557,12857,6455,649,1185,779,"['PC', 'PlayStation', 'Xbox']",['Action'],"(373.0, 7334.0]",['Action']
1,The Witcher 3: Wild Hunt,2015-05-18,4.64,7142,22119,7261,"['Action', 'RPG']","['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...",Singleplayer,1207,12857,5284,850,1025,896,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...","['Action', 'RPG']","(373.0, 7334.0]","['Action', 'RPG']"
2,Portal 2,2011-04-18,4.58,6066,20829,6123,"['Shooter', 'Puzzle']","['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...",Both,672,13095,5843,410,645,164,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh...","['Shooter', 'Puzzle']","(373.0, 7334.0]","['Shooter', 'Puzzle']"
3,Counter-Strike: Global Offensive,2012-08-21,3.57,3626,18342,3664,['Shooter'],"['PC', 'PlayStation', 'Xbox', 'Linux']",Multiplayer,267,14099,1143,80,2120,633,"['PC', 'PlayStation', 'Xbox', 'Linux']",['Shooter'],"(373.0, 7334.0]",['Shooter']
4,Tomb Raider (2013),2013-03-05,4.06,4079,17782,4113,['Action'],"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh']",Both,700,11584,4522,295,564,117,"['PC', 'PlayStation', 'Xbox', 'Apple Macintosh']",['Action'],"(373.0, 7334.0]",['Action']

In [31]:
df_sql = df.drop(columns=['platform_visual', 'genres_visual', 'genres', 'platform', 'genres_clean'])

In [32]:
df_sql.to_csv('df_sql.csv', index= False)

In [33]:
print("Columnas actuales en df_sql:", df_sql.columns.tolist())

Columnas actuales en df_sql: ['name', 'released', 'rating', 'ratings_count', 'added', 'reviews_count', 'game_mode', 'status_yet', 'status_owned', 'status_beaten', 'status_toplay', 'status_dropped', 'status_playing', 'rating_rango']

Genero table

In [41]:
def extract_genres(x):
    if isinstance(x, list):
        # Lista de dicts o strings
        result = []
        for item in x:
            if isinstance(item, dict) and 'name' in item:
                result.append(item['name'])
            elif isinstance(item, str):
                result.append(item)
        return result
    elif isinstance(x, str):
        # Extraer palabras del string, útil si no hay comillas
        return re.findall(r'\b\w+\b', x)
    return []

df['genres_names'] = df['genres'].apply(extract_genres)

all_genres = [g for sublist in df['genres_names'] for g in sublist]
unique_genres = sorted(list(set(all_genres)))  # sorted para orden alfabético

df_genres = pd.DataFrame(unique_genres, columns=['genre'])

In [36]:
df_genres.to_csv("df_genres.csv", index=False)

Platform

In [37]:
def extract_genres(x):
    if isinstance(x, list):
        # Lista de dicts o strings
        result = []
        for item in x:
            if isinstance(item, dict) and 'name' in item:
                result.append(item['name'])
            elif isinstance(item, str):
                result.append(item)
        return result
    elif isinstance(x, str):
        # Extraer palabras del string, útil si no hay comillas
        return re.findall(r'\b\w+\b', x)
    return []

df['platform'] = df['platform'].apply(extract_genres)

all_platform = [g for sublist in df['platform'] for g in sublist]
unique_platform = sorted(list(set(all_platform)))  # sorted para orden alfabético

df_platform = pd.DataFrame(unique_platform, columns=['platform'])

In [38]:
df_platform

       platform
0           3DO
1         Amiga
2       Android
3         Apple
4         Atari
5     Commodore
6           Geo
7         Linux
8     Macintosh
9           Neo
10     Nintendo
11           PC
12  PlayStation
13         SEGA
14          Web
15         Xbox
16          iOS

In [39]:
df_platform.to_csv("df_platform.csv", index=False)

Mapeo Game-Genre

In [40]:
# Crear el mapeo juego-género usando la columna 'genres' del df principal
game_genre_mapping = []

for idx, row in df.iterrows():
    game_id = idx  # el id que agregaste como índice
    game_name = row['name']
    
    # Obtener la lista de géneros de la columna 'genres'
    genres_list = row['genres']
    
    # Convertir a lista si es string
    if isinstance(genres_list, str):
        import ast
        try:
            genres_list = ast.literal_eval(genres_list)
        except:
            # Limpiar el string si es necesario
            genres_list = genres_list.strip('[]').replace("'", "").split(', ')
            genres_list = [g.strip() for g in genres_list if g.strip()]
    
    # Para cada género en la lista del juego
    if isinstance(genres_list, list):
        for genre_name in genres_list:
            # Buscar el genre_id en df_genres
            genre_match = df_genres[df_genres['genre'] == genre_name]
            if not genre_match.empty:
                genre_id = genre_match.index[0]
                game_genre_mapping.append({
                    'game_id': game_id,
                    'game_name': game_name,
                    'genre_id': genre_id,
                    'genre_name': genre_name
                })

# Crear DataFrame con el mapeo
df_game_genre_mapping = pd.DataFrame(game_genre_mapping)

# Mostrar resultados
print("Mapeo juego-género (primeras 20 filas):")
print(df_game_genre_mapping.head(20))
print(f"\nTotal de relaciones: {len(df_game_genre_mapping)}")

# Guardar solo las columnas necesarias para SQL
df_game_genre_sql = df_game_genre_mapping[['game_id', 'genre_id']]
df_game_genre_sql.to_csv('game_genre_mapping.csv', index=False)

print("\nArchivo guardado: game_genre_mapping.csv")
print(df_game_genre_sql.head(10))

KeyboardInterrupt:

Mapeo Game-Platform

In [ ]:
# Crear el mapeo juego-plataforma usando la columna 'platform' del df principal
game_platform_mapping = []

for idx, row in df.iterrows():
    game_id = idx  # el id que agregaste como índice
    game_name = row['name']
    
    # Obtener la lista de plataformas de la columna 'platform'
    platforms_list = row['platform']
    
    # Convertir a lista si es string
    if isinstance(platforms_list, str):
        import ast
        try:
            platforms_list = ast.literal_eval(platforms_list)
        except:
            # Limpiar el string si es necesario
            platforms_list = platforms_list.strip('[]').replace("'", "").split(', ')
            platforms_list = [p.strip() for p in platforms_list if p.strip()]
    
    # Para cada plataforma en la lista del juego
    if isinstance(platforms_list, list):
        for platform_name in platforms_list:
            # Buscar el platform_id en df_platform
            platform_match = df_platform[df_platform['platform'] == platform_name]
            if not platform_match.empty:
                platform_id = platform_match.index[0]
                game_platform_mapping.append({
                    'game_id': game_id,
                    'game_name': game_name,
                    'platform_id': platform_id,
                    'platform_name': platform_name
                })

# Crear DataFrame con el mapeo
df_game_platform_mapping = pd.DataFrame(game_platform_mapping)

# Mostrar resultados
print("Mapeo juego-plataforma (primeras 20 filas):")
print(df_game_platform_mapping.head(20))
print(f"\nTotal de relaciones: {len(df_game_platform_mapping)}")

# Guardar solo las columnas necesarias para SQL
df_game_platform_sql = df_game_platform_mapping[['game_id', 'platform_id']]
df_game_platform_sql.to_csv('game_platform_mapping.csv', index=False)

print("\nArchivo guardado: game_platform_mapping.csv")
print(df_game_platform_sql.head(10))

Mapeo juego-plataforma (primeras 20 filas):
    game_id                         game_name  platform_id platform_name
0         0                Grand Theft Auto V           11            PC
1         0                Grand Theft Auto V           12   PlayStation
2         0                Grand Theft Auto V           15          Xbox
3         1          The Witcher 3: Wild Hunt           11            PC
4         1          The Witcher 3: Wild Hunt           12   PlayStation
5         1          The Witcher 3: Wild Hunt           15          Xbox
6         1          The Witcher 3: Wild Hunt           10      Nintendo
7         2                          Portal 2           11            PC
8         2                          Portal 2           12   PlayStation
9         2                          Portal 2           15          Xbox
10        2                          Portal 2            7         Linux
11        3  Counter-Strike: Global Offensive           11            PC
12        3  Counter-Strike: Global Offensive           12   PlayStation
13        3  Counter-Strike: Global Offensive           15          Xbox
14        3  Counter-Strike: Global Offensive            7         Linux
15        4                Tomb Raider (2013)           11            PC
16        4                Tomb Raider (2013)           12   PlayStation
17        4                Tomb Raider (2013)           15          Xbox
18        5                            Portal           11            PC
19        5                            Portal           12   PlayStation

Total de relaciones: 23371

Archivo guardado: game_platform_mapping.csv
   game_id  platform_id
0        0           11
1        0           12
2        0           15
3        1           11
4        1           12
5        1           15
6        1           10
7        2           11
8        2           12
9        2           15

In [ ]:
# Estadísticas de ambos mapeos
print("\nESTADÍSTICAS FINALES ")
print(f"Total juegos: {len(df)}")
print(f"Total géneros únicos: {len(df_genres)}")
print(f"Total plataformas únicas: {len(df_platform)}")
print(f"Total relaciones juego-género: {len(df_game_genre_mapping)}")
print(f"Total relaciones juego-plataforma: {len(df_game_platform_mapping)}")
print(f"Promedio géneros por juego: {len(df_game_genre_mapping) / len(df):.2f}")
print(f"Promedio plataformas por juego: {len(df_game_platform_mapping) / len(df):.2f}")

# Archivos generados
print("\nARCHIVOS GENERADOS ")
print("1. game_genre_mapping.csv (game_id, genre_id)")
print("2. game_platform_mapping.csv (game_id, platform_id)")

ESTADÍSTICAS FINALES
Total juegos: 9846
Total géneros únicos: 21
Total plataformas únicas: 17
Total relaciones juego-género: 25215
Total relaciones juego-plataforma: 23371
Promedio géneros por juego: 2.56
Promedio plataformas por juego: 2.37

ARCHIVOS GENERADOS
1. game_genre_mapping.csv (game_id, genre_id)
2. game_platform_mapping.csv (game_id, platform_id)

Conectar SQL

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Conectar a MySQL
engine = create_engine("mysql+pymysql://root:12345@localhost:3306/videojuegos_db")

# Lista de archivos CSV y sus tablas
archivos = [
    ('df_sql.csv', 'games'),
    ('df_genres.csv', 'genres'),
    ('df_platform.csv', 'platforms'),
    ('game_genre_mapping.csv', 'game_genres'),
    ('game_platform_mapping.csv', 'game_platforms')
]

# Insertar cada archivo
for archivo, tabla in archivos:
    try:
        df = pd.read_csv(archivo)
        df.to_sql(tabla, engine, if_exists='append', index=False)
        print(f"✓ Insertados {len(df)} registros en {tabla}")
    except Exception as e:
        print(f"✗ Error en {tabla}: {e}")

print("Proceso completado")

✓ Insertados 9846 registros en games
✓ Insertados 21 registros en genres
✓ Insertados 17 registros en platforms
✓ Insertados 25215 registros en game_genres
✓ Insertados 23371 registros en game_platforms
Proceso completado